# -*- coding: utf-8 -*-
"""time_series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psxaM-NcI_OXQeJzaTdHBpoiHZgcI4Sm
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose


df_reel = pd.read_csv('trafic_data.csv')

df_reel['Date'] = pd.to_datetime(df_reel['Date'])
df_reel.set_index('Date', inplace=True)



plt.figure(figsize=(12, 6))
plt.plot(df_reel.index, df_reel['Trafic_To'], marker='o', color='#1f77b4', linewidth=2)
plt.title("Évolution du Trafic Data au Maroc (en To)", fontsize=14)
plt.xlabel("Années", fontsize=12)
plt.ylabel("Volume (Téraoctets)", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

decomposition = seasonal_decompose(df_reel['Trafic_To'].dropna(), model='multiplicative', period=4)

fig = decomposition.plot()
fig.set_size_inches(12, 8)

plt.show()

import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller

print("--- TEST DE STATIONNARITÉ (Série brute) ---")
resultat_brut = adfuller(df_reel['Trafic_To'].dropna())
print(f"Le p-value est de : {resultat_brut[1]:.5f}")


df_reel['Trafic_Log'] = np.log(df_reel['Trafic_To'])

# 2. On annule la montée avec la differenciation
df_reel['Trafic_Stationnaire'] = df_reel['Trafic_Log'].diff()

# 3. On nettoie la case vide
donnees_propres = df_reel['Trafic_Stationnaire'].dropna()

# 4. On relance le scanner sur les bonnes données
print("\n--- TEST DE STATIONNARITÉ (Série Transformée) ---")
resl = adfuller(donnees_propres)
p_value_1 = resl[1]

print(f"Le nouveau p-value est de : {p_value_1:.5f}")

if p_value_1 <= 0.05:
    print("Verdict :  La série est prête (Stationnaire) !")
else:
    print("Verdict :  La série n'est PAS stationnaire.")


plt.figure(figsize=(12, 5))
plt.plot(df_reel.index, df_reel['Trafic_Stationnaire'], marker='o', color='green', linewidth=2)
plt.title("Série Parfaitement Stationnaire (Log + Diff)", fontsize=14)
plt.axhline(y=0, color='red', linestyle='--')
plt.xlabel("Années")
plt.ylabel("Variation du Log(Volume)")
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# 1er Radar : L'ACF  - On passe lags à 12
plot_acf(donnees_propres, ax=axes[0], lags=12, title="Autocorrélation (ACF) -> Cherche 'q'")

# 2ème Radar : Le PACF  - On passe lags à 12
plot_pacf(donnees_propres, ax=axes[1], lags=12, title="Autocorrélation Partielle (PACF) -> Cherche 'p'", method='ywm')

plt.show()

import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA


# On garde tout SAUF les 4 derniers trimestres pour l'entraînement
train_log = df_reel['Trafic_Log'].iloc[:-4].dropna()

# On garde UNIQUEMENT les 4 derniers trimestres (en vrais Téraoctets) pour le test final
test_reel = df_reel['Trafic_To'].iloc[-4:]

print(f" Phase d'apprentissage sur : {len(train_log)} trimestres")
print(f" Phase de test (données cachées) sur : {len(test_reel)} trimestres\n")

# ---------------------------------------------------------
# 2. L'ENTRAÎNEMENT & LA PRÉDICTION
# ---------------------------------------------------------
modele_test = ARIMA(train_log, order=(1, 1, 1))
resultats_test = modele_test.fit()

previsions_log_test = resultats_test.forecast(steps=4)

previsions_reelles_test = np.exp(previsions_log_test)

# ---------------------------------------------------------
# 3. LE CALCUL DU SCORE (MAPE)
# ---------------------------------------------------------
erreurs_absolues = np.abs((test_reel.values - previsions_reelles_test.values) / test_reel.values)
mape = np.mean(erreurs_absolues) * 100
fiabilite = 100 - mape

print("---  VERDICT DU BACKTESTING ---")
print(f"Marge d'erreur moyenne (MAPE) : {mape:.2f} %")
print(f"Fiabilité du modèle ARIMA    : {fiabilite:.2f} %\n")

plt.figure(figsize=(12, 6))

plt.plot(df_reel.index[:-4], df_reel['Trafic_To'].iloc[:-4], label="Passé (Données d'entraînement)", color='#1f77b4', marker='o')

plt.plot(test_reel.index, test_reel, label="Réalité (Ce qu'il fallait trouver)", color='green', marker='o', linewidth=2.5)

plt.plot(previsions_reelles_test.index, previsions_reelles_test, label="Prédiction de l'ARIMA", color='red', marker='X', linestyle='--', linewidth=2.5)

plt.title(f"Test de Fiabilité - Précision à {fiabilite:.2f}%", fontsize=16, fontweight='bold')
plt.xlabel("Années")
plt.ylabel("Volume (Téraoctets)")
plt.legend(fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA

print(" Lancement des prévisions officielles pour 2026-2027...")

# ---------------------------------------------------------
# 1. ENTRAÎNEMENT SUR 100% DES DONNÉES
# ---------------------------------------------------------
# On utilise toute la série Log pour un maximum d'intelligence
modele_final = ARIMA(df_reel['Trafic_Log'].dropna(), order=(1, 1, 1))
resultats_finaux = modele_final.fit()

# ---------------------------------------------------------
# 2. PRÉDICTION SUR 2 ANS (8 trimestres)
# ---------------------------------------------------------
horizon = 8
previsions_detaillees = resultats_finaux.get_forecast(steps=horizon)

#  L'Antidote (Exponentielle) pour repasser en Téraoctets
previsions_moyennes = np.exp(previsions_detaillees.predicted_mean)
marges_erreur = previsions_detaillees.conf_int()
borne_basse = np.exp(marges_erreur.iloc[:, 0])
borne_haute = np.exp(marges_erreur.iloc[:, 1])

# ---------------------------------------------------------
# 3. EXPORTATION DES DONNÉES
# ---------------------------------------------------------
tableau_final = pd.DataFrame({
    'Prevision_To': previsions_moyennes.round(0), # On arrondit pour faire propre
    'Borne_Basse_To': borne_basse.round(0),
    'Borne_Haute_To': borne_haute.round(0)
})

print("\n Aperçu des futurs volumes à prévoir :")
print(tableau_final.head())

# Sauvegarde physique du fichier
tableau_final.to_csv('Previsions_Trafic_2026_2027.csv')
print("\n Fichier 'Previsions_Trafic_2026_2027.csv' sauvegardé avec succès dans tes dossiers !")

# ---------------------------------------------------------
# 4. LE GRAPHIQUE ULTIME
# ---------------------------------------------------------
plt.figure(figsize=(14, 6))

plt.plot(df_reel.index, df_reel['Trafic_To'], label="Historique (Jusqu'à fin 2025)", color='#1f77b4', marker='o', linewidth=2)

plt.plot(previsions_moyennes.index, previsions_moyennes, label="Prévisions 2026-2027", color='red', marker='X', linestyle='--', linewidth=2.5)

plt.fill_between(previsions_moyennes.index, borne_basse, borne_haute, color='red', alpha=0.15, label="Marge d'erreur à 95%")

plt.title("Prévisions Officielles du Trafic Internet (2026-2027)", fontsize=16, fontweight='bold')
plt.xlabel("Années", fontsize=12)
plt.ylabel("Volume (Téraoctets)", fontsize=12)
plt.legend(fontsize=12, loc='upper left')
plt.grid(True, linestyle='--', alpha=0.6)

plt.show()

# --- ÉTAPE 6 : DIAGNOSTIC DES RÉSIDUS (Validation du modèle) ---
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.stats.diagnostic import acorr_ljungbox


resid = resultats_finaux.resid

fig, ax = plt.subplots(2, 2, figsize=(15, 10))

ax[0, 0].plot(resid)
ax[0, 0].set_title('1. Graphique des Résidus (Doit être plat et aléatoire)')
ax[0, 0].axhline(0, color='red', linestyle='--')

sns.histplot(resid, kde=True, ax=ax[0, 1], color='blue')
ax[0, 1].set_title('2. Distribution (Doit suivre une courbe en cloche/Normale)')

plot_acf(resid, ax=ax[1, 0], lags=20)
ax[1, 0].set_title('3. Autocorrélation des résidus (ACF)')

stats.probplot(resid, dist="norm", plot=ax[1, 1])
ax[1, 1].set_title('4. QQ-Plot')

plt.tight_layout()
plt.show()

# --- TEST STATISTIQUE DE LJUNG-BOX ---
print("--- Résultat du test de Ljung-Box ---")
ljung_box_results = acorr_ljungbox(resid, lags=[10], return_df=True)
print(ljung_box_results)
print("\nInterprétation : Si la p-value est > 0.05, les résidus sont indépendants (Le modèle est parfait).")
